'use client'

import { useState } from 'react'

const email = 'mailto:proyecto@intrepidux.com'
const whatsapp = 'https://wa.me/18296101505'
const heroImage = 'https://pub-11d708cf2b2a4cfc8a75cc66a852c138.r2.dev/intrepidux/INTREPIDUX%20hero-Photoroom.png'
const iconosImage = 'https://pub-11d708cf2b2a4cfc8a75cc66a852c138.r2.dev/intrepidux/iconos.png'

const problems = ['Equipo técnico senior — +10 años desarrollando soluciones empresariales. Consultores funcionales y desarrolladores certificados en cada proyecto.', 'Adaptación a tu negocio — No forzamos plantillas. Mapeamos tus procesos reales y configuramos la solución para encajar con tu operación.', 'Enfoque en resultados — Cada implementación tiene KPIs medibles desde el día uno. Te enseñamos a leer el ROI, no solo a usar el sistema.', 'Implementaciones escalables — Arquitectura modular pensada para crecer contigo: empieza con lo esencial y expande sin reconstruir.']
const steps = [['Diagnóstico', 'Entendemos tu operación, identificamos cuellos de botella y definimos un alcance claro con KPIs medibles.'], ['Implementación', 'Configuramos los módulos, migramos tus datos, desarrollamos lo personalizado y validamos cada flujo.'], ['Capacitación', 'Entrenamos a tu equipo con sesiones prácticas y dejamos documentación viva para nuevos usuarios.'], ['Soporte continuo', 'Acompañamos el día a día, optimizamos procesos y evolucionamos la plataforma con tu negocio.']]
const industries = [['Construcción', 'Proyectos, presupuestos, compras, subcontratos, costos, avances y control de obra.'], ['Servicios profesionales', 'Proyectos, horas, clientes, facturación, gastos y rentabilidad por servicio.'], ['Comercio y distribución', 'Inventario, compras, ventas, puntos de venta, almacenes y logística.'], ['Manufactura', 'Producción, materiales, órdenes de trabajo, costos y control de calidad.'], ['Salud y bienestar', 'Citas, pacientes, servicios, expedientes, cobros y seguimiento.'], ['Educación', 'Estudiantes, pagos, calendarios, comunicación, cursos y reportes.']]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="site-shell">
    <section className="hero" id="top"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" />
      <nav className="nav" aria-label="Navegación principal"><a className="brand" href="#top" aria-label="Intrepidux inicio"><img src="/intrepidux-logo.png" alt="Intrepidux" /></a><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="nav-links" onClick={() => setMenuOpen(!menuOpen)}><span>{menuOpen ? 'Cerrar' : 'Menú'}</span><span className="menu-icon">{menuOpen ? '×' : '☰'}</span></button><div className={`nav-links ${menuOpen ? 'nav-links-open' : ''}`} id="nav-links"><a href="#servicios">Servicios</a><a href="#sectores">Sectores</a><a href="#proceso">Proceso</a><a href="#clientes">Clientes</a><a href="#contacto">Contacto</a></div><div className="nav-actions"><a href={email} className="button button-orange">Agendar Consultoría <span>↗</span></a></div></nav>
      <div className="hero-content"><p className="eyebrow light">Transformación digital para empresas que escalan</p><h1>Más que un proveedor:<br /><em>un socio estratégico.</em></h1><p className="hero-description">Llevamos +10 años construyendo soluciones digitales a medida. Mapeamos tus procesos reales, configuramos tecnología que encaja y medimos ROI desde el día uno — sin plantillas forzadas, sin dependencia de un solo vendor.</p><div className="hero-actions"><a href={email} className="button button-orange">Agendar Consultoría <span>↗</span></a><a href="#sectores" className="text-link">Ver soluciones <span>→</span></a></div><img className="hero-laptop" src={heroImage} alt="Software de gestión empresarial Intrepidux en una computadora portátil" /></div><div className="hero-footer"><span>Soluciones para hacer crecer tu negocio.</span><span className="scroll-note">Explorar <b>↓</b></span><span>República Dominicana</span></div>
    </section>
    <section className="problem-section section-pad" id="problema"><div className="section-kicker"><span>01 / POR QUÉ NOSOTROS</span><span>Más que un proveedor: un socio estratégico.</span></div><div className="intro-grid"><h2>Más que un proveedor,<br /><span>un socio estratégico.</span></h2><p className="large-copy">Muchas empresas tienen clientes, ventas y un equipo comprometido, pero el crecimiento empieza a sentirse pesado. La información se fragmenta, los procesos se vuelven manuales y cada nueva oportunidad exige más esfuerzo del que debería.</p></div><div className="problem-grid">{problems.map((problem, index) => <article className="problem-card" key={problem}><span>0{index + 1}</span><p>{problem}</p></article>)}</div></section>
    <section className="intro section-pad" id="proceso"><div className="section-kicker"><span>02 / NUESTRA METODOLOGÍA</span><span>Un proceso claro desde la interacción inicial hasta el soporte continuo.</span></div><div className="intro-grid"><h2>Construimos tu éxito,<br /><span>paso a paso.</span></h2><div><p className="large-copy">Un proceso claro, humano y personalizado para comprender tu operación y convertir tus retos en soluciones tecnológicas.</p><p className="muted-copy">Te acompañamos desde la primera conversación hasta que tu sistema evoluciona contigo.</p></div></div><div className="capability-grid process-cards">{steps.map(([title, text], index) => <article className={`capability-card ${['coral', 'gold', 'blue', 'coral'][index]}`} key={title}><span className="card-number">0{index + 1}</span><div className="card-symbol">{['⌁', '↗', '◌', '＋'][index]}</div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="capabilities section-pad" id="sectores"><div className="section-kicker"><span>03 / SECTORES</span><span>Soluciones especializadas para cada industria y etapa de crecimiento.</span></div><div className="industry-grid">{industries.map(([title, text], index) => <article className="industry-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><b>Control · Trazabilidad · Crecimiento</b></article>)}</div></section>
    <section className="references-blue section-pad" id="clientes"><div className="section-kicker"><span>04 / CLIENTES</span><span>Empresas que ya operan con nuestras soluciones.</span></div><div className="references-image-wrap"><img src={iconosImage} alt="Soluciones integradas de Intrepidux" /></div></section>
    <section className="contact-section section-pad" id="contacto"><div className="contact-copy"><div className="section-kicker"><span>05 / Contacto</span></div><h2>Hablemos de<br /><span>tu proyecto.</span></h2><p>Cuéntanos brevemente qué necesita tu negocio. Revisamos tu caso y te decimos con franqueza si te conviene un sistema a medida.</p><div className="contact-details"><p><strong>Email:</strong> <a href={email}>proyecto@intrepidux.com</a></p><p><strong>WhatsApp:</strong> <a href={whatsapp}>+1 (829) 610-1505</a></p><p><strong>Dirección:</strong> Calle 19 Este #20, San Gerónimo, Santo Domingo, Distrito Nacional</p></div></div><form className="contact-form" action={email} method="post"><label>Nombre y apellido<input name="name" placeholder="Tu nombre" required /></label><label>Empresa<input name="company" placeholder="Nombre de tu empresa" required /></label><label>Teléfono o WhatsApp<input name="phone" type="tel" placeholder="Tu teléfono" required /></label><label>Correo de trabajo<input name="email" type="email" placeholder="tu@empresa.com" required /></label><label>Sector<select name="sector" defaultValue=""><option value="" disabled>Selecciona tu sector</option><option>Manufactura</option><option>Distribución</option><option>Tecnología & IT</option><option>Salud</option><option>Construcción</option><option>Otra industria</option></select></label><label>Personas trabajando<select name="team" defaultValue=""><option value="" disabled>Selecciona una opción</option><option>1 a 15</option><option>16 a 50</option><option>Más de 50</option></select></label><fieldset className="full-field"><legend>¿Dónde llevan su información hoy?</legend>{['Hojas de cálculo (Excel / Drive)', 'Un sistema contable básico', 'Varios programas separados', 'Sistema propio viejo'].map(item => <label className="check-label" key={item}><input type="checkbox" name="systems" value={item} /> {item}</label>)}</fieldset><label className="full-field">¿Cuál es el problema principal que quieren resolver hoy?<textarea name="message" rows={4} placeholder="Ej: El inventario nunca cuadra, tardamos días en facturar, o no sabemos cuánto rinde cada obra..." required /></label><button className="button button-orange" type="submit">Pedir diagnóstico gratuito <span>↗</span></button><span className="form-note">Respuesta en menos de 24 horas. Cero spam.</span></form></section>
    <footer className="footer"><div className="footer-top"><a className="brand footer-brand" href="#top"><img src="/intrepidux-logo.png" alt="Intrepidux" /></a><p>Gestiona, crece y triunfa con nosotros. Transformación digital para empresas que quieren operar con datos, no con suposiciones.<br /><br />Calle 19 Este #20, San Gerónimo, Santo Domingo, Distrito Nacional</p><div className="footer-links"><div><small>Explorar</small><a href="#problema">El problema</a><a href="#servicios">Servicios</a><a href="#referencias">Referencias</a><a href="#contacto">Contacto</a></div><div><small>Contacto</small><a href={email}>proyecto@intrepidux.com</a><a href={whatsapp}>WhatsApp</a></div></div></div><div className="footer-bottom"><span>© Intrepidux S.R.L.</span><span>Todos los derechos reservados.</span></div></footer>
  </main>
}
